package frank.password_manager.UI;

import frank.password_manager.DAO.PasswordDAO;
import frank.password_manager.Models.Password;
import frank.password_manager.Utils.Tools;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class AgregarPassPNL extends javax.swing.JPanel {

    private PasswordDAO dao;

    public AgregarPassPNL() {
        initComponents();
        dao = PasswordDAO.getInstance();
        Tools.loadIntoCombobox(categoriaCBOX, dao.getAllCategories());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        serviceTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passTF = new javax.swing.JPasswordField();
        userTF = new javax.swing.JTextField();
        acceptBTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        categoriaCBOX = new javax.swing.JComboBox<>();
        newCateBTN = new javax.swing.JButton();
        volverBTN = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nombre del servicio");

        serviceTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre de usuario");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña");

        passTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        userTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        acceptBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acceptBTN.setText("Aceptar");
        acceptBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBTNActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Categoria");

        categoriaCBOX.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        categoriaCBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        newCateBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newCateBTN.setText("Nueva categoria");
        newCateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCateBTNActionPerformed(evt);
            }
        });

        volverBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Agregando contraseña");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverBTN)
                .addGap(18, 18, 18)
                .addComponent(acceptBTN)
                .addGap(398, 398, 398))
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(userTF)
                    .addComponent(passTF)
                    .addComponent(serviceTF)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(categoriaCBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newCateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(303, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serviceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriaCBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCateBTN))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptBTN)
                    .addComponent(volverBTN))
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void acceptBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBTNActionPerformed

        String serviceName = Tools.capitalize(serviceTF.getText());
        String username = userTF.getText();
        String password = String.valueOf(passTF.getPassword());
        String category = String.valueOf(categoriaCBOX.getSelectedItem());

        Password newPassword = new Password(serviceName, username, password, category);

        try {
            if (dao.savePassword(newPassword)) {
                JOptionPane.showInternalMessageDialog(null, "Se ha agregado la contraseña", "Exito", JOptionPane.INFORMATION_MESSAGE);
                Tools.changePanel(new DashboardPNL(), (JPanel) this.getParent());
            }
        } catch (Exception ex) {
            JOptionPane.showInternalMessageDialog(null, "Ocurrio un error : " + ex.toString(), "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_acceptBTNActionPerformed

    private void newCateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCateBTNActionPerformed
        String newCategory = Tools.capitalize(JOptionPane.showInputDialog(this.getParent(), "Introduce nueva categoría:"));
        if (newCategory != null && !newCategory.trim().isEmpty()) {
            categoriaCBOX.addItem(newCategory);  // Agregar nueva categoría al ComboBox
            categoriaCBOX.setSelectedItem(newCategory);  // Seleccionar la nueva categoría
        }
    }//GEN-LAST:event_newCateBTNActionPerformed

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        Tools.changePanel(new DashboardPNL(), (JPanel) this.getParent());
    }//GEN-LAST:event_volverBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptBTN;
    private javax.swing.JComboBox<String> categoriaCBOX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newCateBTN;
    private javax.swing.JPasswordField passTF;
    private javax.swing.JTextField serviceTF;
    private javax.swing.JTextField userTF;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
