/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frank.password_manager.UI;

import frank.password_manager.DAO.PasswordDAO;
import frank.password_manager.Models.Password;
import frank.password_manager.Utils.Tools;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author fran
 */
public class EditPassPNL extends javax.swing.JPanel {

    private PasswordDAO dao;

    public EditPassPNL(Password password) {
        initComponents();
        dao = PasswordDAO.getInstance();
        loadData(password);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        serviceTF = new javax.swing.JTextField();
        userTF = new javax.swing.JTextField();
        cateCBOX = new javax.swing.JComboBox<>();
        newCatBTN = new javax.swing.JButton();
        guardarBTN = new javax.swing.JButton();
        passTF = new javax.swing.JTextField();
        backBTN = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Editando contraseña");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Id");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nombre del servicio");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Nombre de usuario o correo");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Contraseña");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Categoria");

        idTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        serviceTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        userTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cateCBOX.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cateCBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        newCatBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newCatBTN.setText("Nueva");
        newCatBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCatBTNActionPerformed(evt);
            }
        });

        guardarBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        guardarBTN.setText("Guardar");
        guardarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBTNActionPerformed(evt);
            }
        });

        passTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        backBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backBTN.setText("Volver");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(guardarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(passTF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cateCBOX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(newCatBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(idTF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(serviceTF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(userTF, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(serviceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cateCBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCatBTN))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBTN)
                    .addComponent(guardarBTN))
                .addContainerGap(101, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guardarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBTNActionPerformed

        Long id = Long.valueOf(idTF.getText());
        String service = serviceTF.getText();
        String username = userTF.getText();
        String password = passTF.getText();
        String category = cateCBOX.getSelectedItem().toString();

        try {
            if (dao.updatePassword(new Password(id, service, username, password, category))) {
                JOptionPane.showInternalMessageDialog(null, "Se ha actualizado la contraseña", "Exito", JOptionPane.INFORMATION_MESSAGE);
                Tools.changePanel(new DashboardPNL(), (JPanel) this.getParent());
            } else {
                JOptionPane.showInternalMessageDialog(null, "No hubo cambios", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showInternalMessageDialog(null, "Ocurrio un error : " + e.toString(), "Error", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_guardarBTNActionPerformed

    private void newCatBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCatBTNActionPerformed
        String newCategory = Tools.capitalize(JOptionPane.showInputDialog(this.getParent(), "Introduce nueva categoría:"));
        if (newCategory != null && !newCategory.trim().isEmpty()) {
            cateCBOX.addItem(newCategory);  // Agregar nueva categoría al ComboBox
            cateCBOX.setSelectedItem(newCategory);  // Seleccionar la nueva categoría
        }
    }//GEN-LAST:event_newCatBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        Tools.changePanel(new DashboardPNL(), (JPanel) this.getParent());
    }//GEN-LAST:event_backBTNActionPerformed

    private void loadData(Password password) {
        idTF.setText(String.valueOf(password.getId()));
        serviceTF.setText(password.getServiceName());
        userTF.setText(password.getUsername());
        passTF.setText(password.getPassword());
        Tools.loadIntoCombobox(cateCBOX, dao.getAllCategories());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JComboBox<String> cateCBOX;
    private javax.swing.JButton guardarBTN;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton newCatBTN;
    private javax.swing.JTextField passTF;
    private javax.swing.JTextField serviceTF;
    private javax.swing.JTextField userTF;
    // End of variables declaration//GEN-END:variables
}
